{
 "title": "Vaccination Rates",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "3s",
 "panels": [
  {
   "title": "Vaccination Rates by State ( Spark )",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Vaccination Distribution By State",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select city,enroll from city_enroll; \n\n\n\n"
    }
   ]
  },
  {
   "title": "Vaccination Distribution By State",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select city,enroll from city_enroll; \n\n\n\n"
    }
   ]
  },
  {
   "title": "Vaccination Distribution By State",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select city,enroll from city_enroll; \n\n\n\n"
    }
   ]
  },
  {
   "title": "Vaccination Rates by State ( Hadoop )",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 }
  },
  {
   "title": "Low States Vaccination Rates",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select state,mmr from state_mmr where mmr <85 allow filtering; \n\n\n\n"
    },
    {
     "target": "select state,mmr from state_mmr where mmr <93 and mmr >85 allow filtering; \n\n\n\n"
    }
   ]
  },
  {
   "title": "High States Vaccination Rates",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "select state,mmr from state_mmr where mmr >96 allow filtering; \n\n\n\n"
    },
    {
     "target": "select state,mmr from state_mmr where mmr >93 and mmr <96 allow filtering; \n\n\n\n"
    }
   ]
  },
  {
   "title": "Vaccination Thresholds by State",
   "type": "histogram",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 52 },
   "targets": [
    {
     "target": "select state,mmr from state_mmr where mmr > 96 allow filtering; \n"
    },
    {
     "target": "select state,mmr from state_mmr where mmr > 93 and mmr < 96 allow filtering; \n"
    },
    {
     "target": "select state,mmr from state_mmr where mmr > 85 and mmr < 93 allow filtering; \n"
    },
    {
     "target": "select state,mmr from state_mmr where mmr < 85 allow filtering; \n"
    }
   ]
  }
 ]
}